- name: Checkout the GUI repository
  git:
    repo: 'https://github.com/zdevelopers/zeps-gui.git'
    version: master
    dest: build/gui

- name: Install frontend dependencies
  command:
    cmd: npm install --save-dev
    chdir: build/gui

- name: Build the app for production
  command:
    cmd: npm run prod
    chdir: build/gui

- name: Cleanup the frontend build dependencies
  file:
    state: absent
    path: build/gui/node_modules
